packages:
  - modules/*
overrides:
  react-native-reanimated: 4.5.1
  react-native-worklets: 0.10.1

allowBuilds:
  esbuild: true
  unrs-resolver: true

patchedDependencies:
  react-native-webrtc@124.0.8: patches/react-native-webrtc@124.0.8.patch
