apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.relaiscameraengine'
version = '0.1.0'

android {
  namespace 'expo.modules.relaiscameraengine'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  sourceSets.main.assets.srcDirs += ['../fixtures']
}
